// <auto-generated />
using FifaCardApi.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FifaCardApi.Repository.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20230524023552_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FifaCardApi.Domain.Data.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Defending")
                        .HasColumnType("smallint");

                    b.Property<short>("Dribbling")
                        .HasColumnType("smallint");

                    b.Property<short>("Pace")
                        .HasColumnType("smallint");

                    b.Property<short>("Passing")
                        .HasColumnType("smallint");

                    b.Property<short>("Physicality")
                        .HasColumnType("smallint");

                    b.Property<short>("Shooting")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("FifaCardApi.Domain.Data.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("FifaCardApi.Domain.Data.Player", b =>
                {
                    b.HasOne("FifaCardApi.Domain.Data.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
